#############################################################################
# Makefile for building: bat
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ????? 3 08:49:06 2017
# Project:  bat.pro
# Template: app
# Command: /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/bin/qmake -spec /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/linux-g++-mx5x -o Makefile bat.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-mx51-linux-gnueabi-gcc
CXX           = arm-mx51-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fsigned-char -march=armv7-a -mfpu=neon -mfloat-abi=softfp -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -fsigned-char -march=armv7-a -mfpu=neon -mfloat-abi=softfp -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/linux-g++-mx5x -I. -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/include/QtCore -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/include/QtNetwork -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/include/QtGui -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/include -I. -I. -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/include -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/include/glib-2.0 -I/usr/arm-mx51-linux-gnueabi/usr/lib/glib-2.0/include -I/usr/arm-mx51-linux-gnueabi/usr/include/gstreamer-0.10 -I/usr/arm-mx51-linux-gnueabi/usr/include/libxml2 -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/include/freetype2 -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/include/dbus-1.0 -I/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/lib/dbus-1.0/include
LINK          = arm-mx51-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/QT4/lib
LIBS          = $(SUBLIBS)  -L/usr/arm-mx51-linux-gnueabi/usr/lib -L/usr/arm-mx51-linux-gnueabi/usr/local/QT4/lib -lrt -lglib-2.0 -lgthread-2.0 -ldbus-1 -lgstreamer-0.10 -lxml2 -lz -lgmodule-2.0 -lgobject-2.0 -lts -lasound -lxcb -lXau -lXext -lXrender -lX11 -lfreetype -lexpat -ljpeg -lfontconfig -lSM -lICE -lpng -lgsl -lEGL -lGLESv2 -lgsl-fsl -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = arm-mx51-linux-gnueabi-ar cqs
RANLIB        = arm-mx51-linux-gnueabi-ranlib
QMAKE         = /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-mx51-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o \
		qrc_res.o
DIST          = /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/qconfig.pri \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt_functions.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt_config.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/exclusive_builds.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/default_pre.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/release.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/default_post.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/warn_on.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/unix/thread.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/moc.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/resources.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/uic.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/yacc.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/lex.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/include_source_dir.prf \
		bat.pro
QMAKE_TARGET  = bat
DESTDIR       = 
TARGET        = bat

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow_sn.h ui_mainwindow_min.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bat.pro  /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/linux-g++-mx5x/qmake.conf /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/qconfig.pri \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt_functions.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt_config.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/exclusive_builds.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/default_pre.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/release.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/default_post.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/warn_on.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/unix/thread.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/moc.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/resources.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/uic.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/yacc.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/lex.prf \
		/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/linux-g++-mx5x -o Makefile bat.pro
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/qconfig.pri:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt_functions.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt_config.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/exclusive_builds.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/default_pre.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/release.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/default_post.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/warn_on.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/qt.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/unix/thread.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/moc.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/resources.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/uic.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/yacc.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/lex.prf:
/home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /home/developer/arm-mx51/arm-mx51-linux-gnueabi/arm-mx51-linux-gnueabi/sysroot/usr/local/QT4/mkspecs/linux-g++-mx5x -o Makefile bat.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/bat1.0.0 || $(MKDIR) .tmp/bat1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/bat1.0.0/ && $(COPY_FILE) --parents mainwindow.h .tmp/bat1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/bat1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/bat1.0.0/ && $(COPY_FILE) --parents mainwindow_sn.ui mainwindow_min.ui .tmp/bat1.0.0/ && (cd `dirname .tmp/bat1.0.0` && $(TAR) bat1.0.0.tar bat1.0.0 && $(COMPRESS) bat1.0.0.tar) && $(MOVE) `dirname .tmp/bat1.0.0`/bat1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bat1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/arm-mx51-linux-gnueabi/usr/local/QT4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		css/dark.css \
		css/green.css \
		css/grey.css
	/usr/arm-mx51-linux-gnueabi/usr/local/QT4/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow_sn.h ui_mainwindow_min.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow_sn.h ui_mainwindow_min.h
ui_mainwindow_sn.h: mainwindow_sn.ui
	/usr/arm-mx51-linux-gnueabi/usr/local/QT4/bin/uic mainwindow_sn.ui -o ui_mainwindow_sn.h

ui_mainwindow_min.h: mainwindow_min.ui
	/usr/arm-mx51-linux-gnueabi/usr/local/QT4/bin/uic mainwindow_min.ui -o ui_mainwindow_min.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow_min.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

